steps:
# Run tests.
- name: 'golang:stretch'
  entrypoint: 'go'
  args: ['test', './...']

# Build the gke-deploy binary and put into the builder image.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$_PROJECT_ID/gke-deploy'
  # Regional AR Mirrors
  - '--tag=europe-docker.pkg.dev/$_PROJECT_ID/ga/v1/gke-deploy'
  - '--tag=asia-docker.pkg.dev/$_PROJECT_ID/ga/v1/gke-deploy'
  - '--tag=us-docker.pkg.dev/$_PROJECT_ID/ga/v1/gke-deploy'
  - '.'
- name: 'gcr.io/$_PROJECT_ID/gke-deploy'
  args: ['--help']

images:
- 'gcr.io/$_PROJECT_ID/gke-deploy'
# Regional AR Mirrors
- 'europe-docker.pkg.dev/$_PROJECT_ID/ga/v1/gke-deploy'
- 'asia-docker.pkg.dev/$_PROJECT_ID/ga/v1/gke-deploy'
- 'us-docker.pkg.dev/$_PROJECT_ID/ga/v1/gke-deploy'

timeout: 6000s
