steps:
- name: 'node'
  entrypoint: 'yarn'
  args: ['install']
- name: 'node'
  entrypoint: 'yarn'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$_PROJECT_ID/hello_yarn', '.']

images: ['gcr.io/$_PROJECT_ID/hello_yarn']
