steps:
- name: gcr.io/cloud-builders/docker
  args:
  - 'build'
  - '--tag=gcr.io/pacific-ethos-388512/curl'
  # Regional AR Mirrors
  - '--tag=europe-docker.pkg.dev/pacific-ethos-388512/ga/v1/curl'
  - '--tag=asia-docker.pkg.dev/pacific-ethos-388512/ga/v1/curl'
  - '--tag=us-docker.pkg.dev/pacific-ethos-388512/ga/v1/curl'
  - '.'
  dir: 'curl'
# Print version information.
- name: gcr.io/pacific-ethos-388512/curl
  args: ['-V']

# GET data from a server, specifying an Authorization header.
- name: gcr.io/pacific-ethos-388512/curl
  args: ['-o', 'file.out', "--header", "Authorization: Bearer foobar'", 'https://www.example.com']

# POST information to a server, specifying a Content-type header.
- name: gcr.io/pacific-ethos-388512/curl
  args: ['--header', 'Content-type: application/json"', '--data', '"{\"buildID\": \"$BUILD_ID\"}"', 'https://www.example.com']

images:
 - 'gcr.io/pacific-ethos-388512/curl'
 # Regional AR Mirrors
 - 'europe-docker.pkg.dev/pacific-ethos-388512/ga/v1/curl'
 - 'us-docker.pkg.dev/pacific-ethos-388512/ga/v1/curl'
 - 'asia-docker.pkg.dev/pacific-ethos-388512/ga/v1/curl'
